apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/kube-controller-manager/kube-controller-manager.kubeconfig
    - --authorization-kubeconfig=/etc/kubernetes/kube-controller-manager/kube-controller-manager.kubeconfig
    - --bind-address=0.0.0.0
    - --client-ca-file=/etc/kubernetes/kube-controller-manager/ca.crt
    - --cluster-cidr={{ k8s_pod_network_cidr }}
    - --cluster-name={{ k8s_cluster_name }}
    - --cluster-signing-cert-file=/etc/kubernetes/kube-controller-manager/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/kube-controller-manager/ca.key
    - --configure-cloud-routes=false
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/kube-controller-manager/kube-controller-manager.kubeconfig
    - --leader-elect=true
    - --leader-elect-lease-duration=15s
    - --leader-elect-renew-deadline=10s
    - --node-cidr-mask-size=24
    - --node-monitor-grace-period=40s
    - --node-monitor-period=5s
    - --profiling=False
    # - --requestheader-client-ca-file=/etc/kubernetes/ssl/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/kube-controller-manager/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/kube-controller-manager/service-account.key
    - --service-cluster-ip-range={{ k8s_service_cluster_ip_range }}
    - --terminated-pod-gc-threshold=12500
    - --use-service-account-credentials=true


    image: k8s.gcr.io/kube-controller-manager:{{ k8s_version }}
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        path: /healthz
        port: 10257
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
    - mountPath: /etc/kubernetes/kube-controller-manager
      name: etc-k8s-controller-manager
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/kube-controller-manager
      type: DirectoryOrCreate
    name: etc-k8s-controller-manager
status: {}
