---

- name: check if kube-controller-manager exists
  stat:
    path: "{{ bin_dir }}/kube-controller-manager"
  register: controller_manager_bin_stat

- name: get version of kube-controller-manager we have
  command: "{{ bin_dir }}/kube-controller-manager --version"
  register: controller_manager_bin_version_output
  when: controller_manager_bin_stat.stat.exists

- name: download kube-controller-manager binary
  get_url:
    url: "{{ download_baseurl }}/kube-controller-manager"
    dest: "{{ bin_dir }}/kube-controller-manager"
    mode: 0775
    force: true
  when: not controller_manager_bin_stat.stat.exists or
        not k8s_version in controller_manager_bin_version_output.stdout
