---

- name: check if kube-scheduler exists
  stat:
    path: "{{ bin_dir }}/kube-scheduler"
  register: scheduler_bin_stat

- name: get version of kube-scheduler we have
  command: "{{ bin_dir }}/kube-scheduler --version"
  register: scheduler_bin_version_output
  when: scheduler_bin_stat.stat.exists

- name: download kube-scheduler binary
  get_url:
    url: "{{ download_baseurl }}/kube-scheduler"
    dest: "{{ bin_dir }}/kube-scheduler"
    mode: 0775
    force: true
  when: not scheduler_bin_stat.stat.exists or
        not k8s_version in scheduler_bin_version_output.stdout
