---
- name: Gather instance facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups.etcd }}"
  connection: ssh

- name: Generate etcd servers private keys
  openssl_privatekey:
    type: ECC
    curve: "{{ etcd_peer.curve }}"
    path: "{{ etcd_pki_dir }}/{{ item }}-server.key"
  loop: "{{ groups.etcd }}"

- name: Generate etcd servers csrs
  openssl_csr:
    path: "{{ etcd_pki_dir }}/{{ item }}-server.csr"
    privatekey_path: "{{ etcd_pki_dir }}/{{ item }}-server.key"
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    extended_key_usage:
      - serverAuth
      - clientAuth
    extended_key_usage_critical: true
    common_name: "{{ item }}-server"
    subject_alt_name:
      - DNS:localhost
      - DNS:{{ item }}
      - IP:127.0.0.1
      - IP:{{ hostvars[item].ansible_default_ipv4.address }}
  loop: "{{ groups.etcd }}"

- name: Generate etcd servers certificates
  openssl_certificate:
    path: "{{ etcd_pki_dir }}/{{ item }}-server.crt"
    csr_path: "{{ etcd_pki_dir }}/{{ item }}-server.csr"
    ownca_path: "{{ etcd_pki_dir }}/etcd-server-ca.crt"
    ownca_privatekey_path: "{{ etcd_pki_dir }}/etcd-server-ca.key"
    provider: ownca
    ownca_not_after: "{{ etcd_peer.expiration }}"
    ownca_digest: "{{ etcd_peer.digest }}"
  loop: "{{ groups.etcd }}"

- name: Generate etcd peers private keys
  openssl_privatekey:
    type: ECC
    curve: "{{ etcd_peer.curve }}"
    path: "{{ etcd_pki_dir }}/{{ item }}-peer.key"
  loop: "{{ groups.etcd }}"

- name: Generate etcd peers csrs
  openssl_csr:
    path: "{{ etcd_pki_dir }}/{{ item }}-peer.csr"
    privatekey_path: "{{ etcd_pki_dir }}/{{ item }}-peer.key"
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    extended_key_usage:
      - serverAuth
      - clientAuth
    extended_key_usage_critical: true
    common_name: "{{ item }}-peer"
    subject_alt_name:
      - DNS:localhost
      - DNS:{{ item }}
      - IP:127.0.0.1
      - IP:{{ hostvars[item].ansible_default_ipv4.address }}
  loop: "{{ groups.etcd }}"

- name: Generate etcd peers certificate
  openssl_certificate:
    path: "{{ etcd_pki_dir }}/{{ item }}-peer.crt"
    csr_path: "{{ etcd_pki_dir }}/{{ item }}-peer.csr"
    ownca_path: "{{ etcd_pki_dir }}/etcd-peer-ca.crt"
    ownca_privatekey_path: "{{ etcd_pki_dir }}/etcd-peer-ca.key"
    provider: ownca
    ownca_not_after: "{{ etcd_peer.expiration }}"
    ownca_digest: "{{ etcd_peer.digest }}"
  loop: "{{ groups.etcd }}"
