---

- name: download etcd release
  ansible.builtin.get_url:
    url: "{{ etcd_archive_url }}"
    dest: "{{ etcd_bin_directory }}/etcd-{{ etcd_version }}.tar.gz"
    owner: "{{ etcd_user.name }}"
    group: "root"
    mode: 0755

- name: unarchive etcd release
  ansible.builtin.unarchive:
    src: "{{ etcd_bin_directory }}/etcd-{{ etcd_version }}.tar.gz"
    dest: "{{ etcd_bin_directory }}/"
    remote_src: true
    owner: "{{ etcd_user.name }}"
    group: "root"
    creates: "{{ etcd_bin_directory }}/etcd-{{ etcd_version }}-linux-amd64"

- name: symlink to desired etcd version
  ansible.builtin.file:
    state: link
    src: "{{ etcd_bin_directory }}/etcd-{{ etcd_version }}-linux-amd64/{{ item }}"
    dest: "{{ etcd_bin_directory }}/{{ item }}"
    owner: "{{ etcd_user.name }}"
    group: root
  with_items:
    - etcd
    - etcdctl

- name: push etcd systemd unit file
  copy:
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0644
    content: |
      [Unit]
      Description=etcd
      Documentation=https://github.com/etcd-io/etcd/
      After=network.target

      [Service]
      User={{ etcd_user.name }}
      ExecStart={{ etcd_bin_directory }}/etcd --config-file {{ etcd_config_directory }}/config.yaml
      Restart=on-failure
      RestartSec=10s
      Type=notify

      [Install]
      WantedBy=multi-user.target
  tags:
    - config

- name: ensure etcd is running and enabled
  ansible.builtin.service:
    name: etcd
    enabled: true
    state: started

