---

- name: docker network
  include: docker_network.yml
  tags:
    - docker-network

- name: deploy tls
  include: tls.yml
  tags:
    - tls

- name: deploy etcd daemon
  include: deploy.yml
  tags:
    - deploy
