- name: CNI | make sure cni dirs exists
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: true
  with_items:
    - /opt/cni/bin
    - /etc/cni/net.d

- name: CNI | Copy cni plugins
  become: true
  unarchive:
    src: "{{ cni_plugins_archive_url }}"
    dest: "/opt/cni/bin"
    mode: 0755
    remote_src: true
