---
- name: "Ensure that mandatory variables are defined properly"
  assert:
    that:
      # The encryption key should be explicitly set by the user
      - encryption_key is defined and encryption_key | length >= 32
      # make sure that a cluster name is set
      - k8s_cluster_name is defined and k8s_cluster_name | length >= 3
