---
- name: Assertions
  include: 00-assertions.yaml
  tags:
    - always

- name: Create User
  include: user.yaml
  tags:
    - user

- name: Install Binaries
  include: install.yaml
  tags:
    - install

- name: Configuration
  include: configure.yaml
  tags:
    - configure

- name: Enable Services
  include: service.yaml
  tags:
    - service
