- name: ensure services are enabled and running on master
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
