- name: Copy k8s node binaries
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ bin_dir }}/kubelet"
    - "{{ bin_dir }}/kube-proxy"

- name: Install some requirements
  package:
    name:
      - socat
      - conntrack
    state: present
