---
- name: set ingress_nginx_manifest_template
  set_fact:
    ingress_nginx_manifest_template: "deploy.yaml.j2"

- name: deploy ingress-nginx controller
  k8s:
    definition: "{{ lookup('template', ingress_nginx_manifest_template) }}"
    kubeconfig: "{{ kubeconfig_dir }}/admin.kubeconfig"
    apply: true
